### ISSUE TITLE
refactor: separate javascript from html

### ISSUE THREAD

**Issue by matthewsong18** [matthewsong18/csc337-final-project#45]
> I think we should move the javascript into individual files. @Claire-Vu? @BaoNguyen09? What do you guys think?

_Originally posted by @matthewsong18 in https://github.com/matthewsong18/csc337-final-project/pull/41#discussion_r1870345403_

- [ ] Create individual javascript files for frontend

**Comment by BaoNguyen09** [comment]
For this issue I will create a folder to store all the script files so that it's more readable in the frontend folder
