### ISSUE TITLE
Fix: Wrap mongodb connect code into an async function

### ISSUE THREAD

**Issue by BaoNguyen09** [matthewsong18/csc337-final-project#51]
## Description
The code in [here](https://github.com/matthewsong18/csc337-final-project/blob/dev/backend/server.js#L10) will cause error since `mongo.connect()` returns a Promise so it should use`await`. 

## Proposed Solution
- [ ] Wrap the whole code (from line 10-16 of `server.js` file) within an async function
- [ ] Call that function before running the server

**Comment by matthewsong18** [comment]
As this was a client-side error and not an error with the code, this will be closed.
